### PR TITLE
Donejs theming!

### PR DESCRIPTION
**Pull request by lkodai**
screen shot 2016-05-10 at 10 58 59 am

👯👯🍻🎉🍻👯👯

### CODE REVIEW

**Comment by adrifolio** [comment]
@lkodai this looks great!

Here's some things that I spotted:

screen shot 2016-05-13 at 8 58 32 am
- [ ] The header nav demo is not displaying correctly:
  screen shot 2016-05-13 at 9 03 45 am
- [x] The dropdown seems to be missing a border on the top:
  screen shot 2016-05-13 at 9 04 09 am
- [ ] The "button" class applied to a div is not showing up:
  screen shot 2016-05-13 at 9 06 42 am
- [ ] The demos under sidebar are showing empty:
  screen shot 2016-05-13 at 9 15 33 am
- [ ] Some menu items are missing on the style guide section (typography, helpers, layout):
  screen shot 2016-05-13 at 9 29 48 am
  vs
  screen shot 2016-05-13 at 9 29 39 am
- [x] There seems to be two slightly different colors for links:
  screen shot 2016-05-13 at 9 13 12 am
- [x] I think having some headings match the color of links makes it look like they are links as well. So a couple of suggestions on that:
  -- Make the headings a tone of gray and use a lighter font-weight
  -- Add "underline" on hover to links

For example:
screen shot 2016-05-13 at 9 17 03 am
- [x] The line height on `<h3>` seems to high right now. Adjusting it to `line-height: normal` seems to work well:
  screen shot 2016-05-13 at 9 38 23 am
  vs
  screen shot 2016-05-13 at 9 38 29 am
- [x] The icon color for open an external site is not matching the link color
  screen shot 2016-05-13 at 9 18 15 am
- [x] The hover color on the side nav menu items is the same as the selected, which makes it look like two are selected when hovering on them. I would adjust that:
  screen shot 2016-05-13 at 9 21 38 am
- [x] Lastly, I think the gray on the logo could be made tad darker as it doesn't work as well as it does right now in the dark header color:
  screen shot 2016-05-13 at 9 01 44 am

**Comment by adrifolio** [comment]
@lkodai one more that I spotted.
- [x] Clicking on the "live example" takes to  "examples/styles/index.html" which is correct but, currently no styles are showing on the sidebar. 

screen shot 2016-05-19 at 7 07 36 pm

But I'm wondering if we should just point to examples/styles/variables.less.html instead, as we do on the homepage CTA. Thoughts?

**Comment by lkodai** [comment]
Hey Adri,

Phew! So I'm leaving any demo fixes for another branch and there are enough working demos to serve purposes for now I think. This PR is already a gigantic change-storm afterall. But I went through your other comments for the better:

screen shot 2016-06-07 at 11 00 13 am

New H3 and H4 don't look like giant links anymore. (And main content links have an underline on hover)

---

screen shot 2016-06-07 at 11 32 16 am
Lighter color is the "active" and the darker color is the hover.

---

screen shot 2016-06-07 at 2 47 26 pm
Also darkened the logo to match the color of the footer. I do think that's better.

---

The dropdown menus don't have top borders on their DocCSS or DoneJS. If it looks unfinished or in error to you maybe we should fix it in both places. And I decided to take the external link icon out altogether, it's a hassle and those links aren't opening in a new window as the icon usually implies, so they aren't very useful.

**Comment by tomgreever** [comment]
@lkodai these changes look great. I see a few small things I can note for later. 

We need to add Quickstart to the dropdown so it's consistent: 
screen shot 2016-06-08 at 8 41 57 am

Also, imo the content area is not wide enough in most cases. So much that the header demo isn't horizontal. 
screen shot 2016-06-08 at 8 43 59 am

Anyway, it has potential to never end so at some point we'll just have to stop, push it to production, and then push small changes as we have time.

**Comment by adrifolio** [comment]
@lkodai thanks so much for all of the updates! Yes, I agree, we should move forward with what we have and then open smaller PR's to tackle pending items.

Great job on this!
:shipit: !

**Comment by lkodai** [comment]
Got Justin approval, going to merge this and open new issues for the little stuff mentioned above that wasn't addressed so we can track them on our EC board.

**Pull request merged**
